### ISSUE TITLE
Question Number not work with pagination

### ISSUE THREAD

**Issue by MominRaza** [GATEOverflow/q2a-qnumbering#1]
in second page number start from 1 instead of 21.

**Comment by arjunsuresh1987** [comment]
It is the expected behaviour. It is only intended to do numbering on a page.

**Comment by arjunsuresh** [comment]
The numbering is only meant for a single page for quickly tracking the questions.

**Comment by MominRaza** [comment]
Okay, but I want it for all pages work with pagination.
How to do this

**Comment by arjunsuresh** [comment]
Thanks for the PR
